### ISSUE TITLE
Exception with python3 proir to python3.3 (e.g. python3.2 used in Debian Wheezy, Ubuntu 12.04 LTS, ...)

### ISSUE THREAD

**Issue by LuHee** [landscapeio/pylint-plugin-utils#2]
Prior to python3.3 function objects do not have a `__qualname__` attribute. This let's `augment_visit` crash with an `AttributeError`. You can reproduce this with pylint-django:

`$ python3.2 /usr/local/bin/pylint --load-plugins pylint_django`
```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pylint_plugin_utils/__init__.py", line 45, in augment_visit
    checker = get_checker(linter, checker_method.__self__.__class__)
AttributeError: 'function' object has no attribute '__self__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 9, in <module>
    load_entry_point('pylint==1.3.1', 'console_scripts', 'pylint')()
  File "/usr/local/lib/python3.2/dist-packages/pylint/__init__.py", line 21, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.2/dist-packages/pylint/lint.py", line 917, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/usr/local/lib/python3.2/dist-packages/pylint/lint.py", line 361, in load_plugin_modules
    module.register(self)
  File "/usr/local/lib/python3.2/dist-packages/pylint_django/common.py", line 29, in register
    apply_augmentations(linter)
  File "/usr/local/lib/python3.2/dist-packages/pylint_django/augmentations/__init__.py", line 96, in apply_augmentations
    augment_visit(linter, TypeChecker.visit_getattr, foreign_key_sets)
  File "/usr/local/lib/python3.2/dist-packages/pylint_plugin_utils/__init__.py", line 47, in augment_visit
    checker = get_checker(linter, get_class(checker_method.__module__, checker_method.__qualname__))
AttributeError: 'function' object has no attribute '__qualname__'
```

**Comment by carlio** [comment]
Sorry but I'll just close this as Python 3.2 is pretty old by now! Feel free to add a PR though but I'll leave it as 'won't fix' otherwise
